id: IE5353356
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T15:57:44+00:00'
last_modified: '2022-06-08T16:28:27.673958+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3435
  title: དབུ་མའི་སྤྱི་དོན་སྐལ་བཟང་མགུལ་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9465':
      image_group_id: I3CN8570
      title: Volume 1 of dbu ma'i spyi don skal bzang mgul rgyan/
      total_pages: 384
      order: 1
      base_file: 9465.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
