id: P007062
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN3435
  title: དབུ་མའི་སྤྱི་དོན་སྐལ་བཟང་མགུལ་རྒྱན།
  author: ''
  volumes:
    882b993f6c9748c49588073669e59fb3:
      image_group_id: I3CN8570
      title: Volume 1 of dbu ma'i spyi don skal bzang mgul rgyan/
      volume_number: 1
      total_pages: 384
      base_file: v001.txt
