id: P007062
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3435
  title: དབུ་མའི་སྤྱི་དོན་སྐལ་བཟང་མགུལ་རྒྱན།
  author: ''
  volumes:
    9e5d7d615dff43dfbaf1bf039fad91ef:
      image_group_id: I3CN8570
      title: ''
      volume_number: 1
      total_pages: 384
ebook_metadata:
  title: དབུ་མའི་སྤྱི་དོན་སྐལ་བཟང་མགུལ་རྒྱན།
  author: ''
  sku: P007062
  cover: cover.jpg
  layers:
  - pagination
